version: '3'

env:
  IMAGE: registry.10.0.0.1.nip.io/realtime-caserates

tasks:
  build:
    cmds: 
      - yarn build
      - touch docs/.nojekyll
      - echo "covid.quartzsoftware.com" > docs/CNAME
  run:
    cmds:
      - docker run -p 81:80 $IMAGE